kind: pipeline
type: docker
name: packmaker

steps:
- name: pre-lock
  image: kalka/drone-entrypoint
  commands:
  - neofetch
  - python -VVV
  - curl -L 'https://get.kalka.io/curseforge.db' > curseforge.db
  - git clone https://git.kalka.io/kalka/wolfpackmaker
- name: lock
  image: kalka/drone-entrypoint
  commands:
  - packmaker -vvvv --config wolfpackmaker/packmaker.conf lock
- name: package
  image: kalka/drone-entrypoint
  commands:
  - zip -r Wolfpack-Vortex.zip wolfpackmaker/wolfpackmaker.py wolfpackmaker/wolfpackmaker.bat instance.cfg mmc-pack.json
  - zip -r config.zip mmc-pack.json
- name: upload
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: api_key
    base_url: https://git.kalka.io
    title: ${DRONE_TAG}
    note: ${DRONE_COMMIT_MESSAGE}
    files:
      - Wolfpack-Vortex.zip
      - config.zip
      - packmaker.lock
  when:
    event: tag

    