kind: pipeline
type: docker
name: packmaker

workspace:
  path: /drone/src

steps:
- name: pre-lock
  image: kalka/drone-entrypoint
  commands:
  - git clone https://git.kalka.io/kalka/wolfpackmaker
  - neofetch
  - python3 -VVV
  - curl -L 'https://get.kalka.io/curseforge.db' > curseforge.db
- name: lock
  image: kalka/drone-entrypoint
  commands:
  - python3 wolfpackmaker/util/lock.py
- name: package
  image: kalka/drone-entrypoint
  commands:
  - zip -r Wolfpack-Vortex.zip wolfpackmaker/wolfpackmaker.py wolfpackmaker/wolfpackmaker.bat wolfpackmaker/requirements.txt wolfpackmaker/multimc.bat .minecraft instance.cfg mmc-pack.json
  - zip -r config.zip .minecraft mmc-pack.json
- name: mod-list
  image: kalka/drone-entrypoint
  commands:
  - python3 wolfpackmaker/raw_mod_list.py Odin
- name: upload
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: api_key
    base_url: https://git.kalka.io
    title: ${DRONE_TAG}
    note: ${DRONE_COMMIT_MESSAGE}
    files:
      - Wolfpack-Vortex.zip
      - config.zip
      - manifest.lock
      - modlist.db
  when:
    event: tag

    